#!"C:\Users\3rd Year Account\AppData\Local\Programs\Python\Python36-32\python.exe"

import cgi

form = cgi.FieldStorage()
firstname = form.getvalue("fname")
lastname = form.getvalue("lname")
gender = form.getvalue("gender")
course = form.getvalue("course")
age = form.getvalue("age")
school = form.getvalue("School")
string_age= str(age)


print("Content-Type: text/html\n\n")
print("<html> <head><title> Welcome </title></head>")
print("<body>")
print("Hello ")
print(firstname)
print(lastname)
print("<br>")
print(gender)
print("<br>")
print(age)
print("<br>")
print(course)
print("<br>")
print(school)
print("</body>")
print("</html>")

f = open("act1.txt","a")
f.write(firstname)
f.write("\n")
f.write(lastname)
f.write("\n")
f.write(gender)
f.write("\n")
f.write(string_age)
f.write("\n")
f.write(course)
f.write(age)
f.write("\n")
f.write(school)
f.write("\n")
f.write("\n")
f.close()